# Generated by Django 3.2.9 on 2023-02-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contacts_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
