# Generated by Django 3.2.9 on 2023-02-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clients',
            unique_together={('name', 'client_code')},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='email',
        ),
    ]
